In [26]:
import numpy as np
import pandas as pd

In [27]:
data = pd.read_csv('https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/639388c2cbc2120a14dcf466e85730eb8be498bb/iris.csv')

In [28]:
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [29]:
features = data.iloc[:,:-1].values
label=data.iloc[:,-1].values

In [30]:
#Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(features,
                                                label,
                                                test_size=0.2,
                                                random_state=23)

In [31]:
#KNN with Bagging Classifier

from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier

algorithm = KNeighborsClassifier()

model = BaggingClassifier(n_estimators=11,
                         base_estimator=algorithm)

model.fit(X_train,y_train)

BaggingClassifier(base_estimator=KNeighborsClassifier(algorithm='auto',
                                                      leaf_size=30,
                                                      metric='minkowski',
                                                      metric_params=None,
                                                      n_jobs=None,
                                                      n_neighbors=5, p=2,
                                                      weights='uniform'),
                  bootstrap=True, bootstrap_features=False, max_features=1.0,
                  max_samples=1.0, n_estimators=11, n_jobs=None,
                  oob_score=False, random_state=None, verbose=0,
                  warm_start=False)

In [32]:
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))

0.9583333333333334
1.0


# Tweaking to show you decision regions

In [54]:
#1. Assume only two features (So that I can show you decision region in XY plane)
finalFeatures = X_train[:,0:2]
#2. Convert the labels into numeric labels(Discrete labels)(1-setosa,2-versicolor,3-virginica)
    finalLabels = pd.DataFrame(y_train).replace(['setosa','versicolor','virginica'],[1,2,3]).values.ravel()
finalFeatures

array([[4.9, 3.1],
       [5.2, 2.7],
       [5.4, 3.9],
       [7.7, 2.8],
       [5. , 3.4],
       [5.4, 3.9],
       [6.5, 2.8],
       [5. , 2.3],
       [5.7, 3. ],
       [6.3, 3.3],
       [6.9, 3.2],
       [4.8, 3.4],
       [5.5, 2.4],
       [4.6, 3.2],
       [6.3, 2.3],
       [6.3, 2.5],
       [4.9, 2.5],
       [7.9, 3.8],
       [4.9, 3.1],
       [5.7, 2.8],
       [7.4, 2.8],
       [6.2, 3.4],
       [5.5, 4.2],
       [6.1, 2.6],
       [5.4, 3. ],
       [7. , 3.2],
       [7.7, 3.8],
       [5.9, 3. ],
       [5. , 3.6],
       [6.5, 3.2],
       [6.7, 3. ],
       [4.7, 3.2],
       [5.8, 2.6],
       [5.1, 3.3],
       [6.4, 2.8],
       [5.5, 2.3],
       [6.8, 2.8],
       [6.4, 2.8],
       [5.8, 2.8],
       [6.3, 2.5],
       [4.9, 3.1],
       [5. , 3.4],
       [6.3, 3.4],
       [4.9, 3. ],
       [4.8, 3.4],
       [6.8, 3. ],
       [5.8, 2.7],
       [5.5, 2.5],
       [4.4, 2.9],
       [5.6, 3. ],
       [6.4, 2.7],
       [6.2, 2.2],
       [6.5,

In [55]:
#Example of Linear Seperability
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()
model1.fit(finalFeatures,finalLabels)

C:\Users\Reena\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Reena\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [58]:
#Package: mlxtend
# pip install mlxtend
import matplotlib.pyplot as plt
from mlxtend.plotting import plot_decision_regions
%matplotlib inline

plot_decision_regions(finalFeatures,finalLabels,clf=model1,legend=2)

ModuleNotFoundError: No module named 'mlxtend'

In [57]:
from sklearn.metrics import confusion_matrix
confusion_matrix(finalLabels,model1.predict(finalFeatures))

array([[37,  1,  0],
       [ 2, 22, 18],
       [ 0,  6, 34]], dtype=int64)

In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
model2 = KNeighborsClassifier()
model2.fit(finalFeatures,finalLabels)

In [36]:
plot_decision_regions(finalFeatures,finalLabels,clf=model2,legend=2)

NameError: name 'plot_decision_regions' is not defined

In [37]:
confusion_matrix(finalLabels,model1.predict(finalFeatures))

NameError: name 'confusion_matrix' is not defined

In [38]:
confusion_matrix(finalLabels,model2.predict(finalFeatures))

NameError: name 'confusion_matrix' is not defined

# SVM Demo

In [39]:
finalLabels

array([1, 2, 1, 3, 1, 1, 2, 2, 2, 3, 3, 1, 2, 1, 2, 3, 3, 3, 1, 2, 3, 3,
       1, 3, 2, 2, 3, 2, 1, 3, 2, 1, 2, 1, 3, 2, 2, 3, 3, 2, 1, 1, 3, 1,
       1, 3, 3, 2, 1, 2, 3, 2, 3, 3, 2, 1, 2, 3, 3, 2, 1, 2, 2, 2, 3, 2,
       2, 3, 3, 3, 1, 3, 2, 1, 3, 3, 1, 2, 2, 3, 1, 1, 2, 1, 2, 2, 1, 3,
       2, 2, 1, 3, 2, 3, 3, 2, 1, 1, 3, 3, 2, 1, 3, 2, 3, 2, 1, 1, 1, 3,
       1, 1, 3, 1, 2, 1, 2, 1, 1, 2], dtype=int64)

In [40]:
from sklearn.svm import SV
model3 = SVC(kernel="linear") #linear classifier

ImportError: cannot import name 'SV' from 'sklearn.svm' (C:\Users\Reena\Anaconda3\lib\site-packages\sklearn\svm\__init__.py)

In [41]:
model3.fit(finalFeatures,finalLabels)

NameError: name 'model3' is not defined

In [42]:
plot_decision_regions(finalFeatures,finalLabels,clf=model3,legend=2)

NameError: name 'plot_decision_regions' is not defined

In [43]:
model4 = SVC(kernel="rbf")

NameError: name 'SVC' is not defined

In [44]:
model4.fit(finalFeatures,finalLabels)

NameError: name 'model4' is not defined

In [45]:
plot_decision_regions(finalFeatures,finalLabels,clf=model4,legend=2)

NameError: name 'plot_decision_regions' is not defined

In [46]:
model5 = SVC(kernel="poly")
model5.fit(finalFeatures,finalLabels)

NameError: name 'SVC' is not defined

In [47]:
plot_decision_regions(finalFeatures,finalLabels,clf=model5,legend=2)

NameError: name 'plot_decision_regions' is not defined

In [48]:
model6 = SVC(kernel="sigmoid")
model6.fit(finalFeatures,finalLabels)

NameError: name 'SVC' is not defined

In [49]:
plot_decision_regions(finalFeatures,finalLabels,clf=model6,legend=2)

NameError: name 'plot_decision_regions' is not defined

In [50]:
confusion_matrix(finalLabels,model3.predict(finalFeatures))

NameError: name 'confusion_matrix' is not defined

In [51]:
confusion_matrix(finalLabels,model4.predict(finalFeatures))

NameError: name 'confusion_matrix' is not defined

In [52]:
confusion_matrix(finalLabels,model5.predict(finalFeatures))

NameError: name 'confusion_matrix' is not defined

In [53]:
confusion_matrix(finalLabels,model6.predict(finalFeatures))

NameError: name 'confusion_matrix' is not defined